### ISSUE TITLE
[BUG] Homebridge initialisation gives error Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by thewinger** [arendruni/homebridge-pihole#4]
**Describe the bug**
Install with `npm install -g homebridge-pihole`
Added 

```
        {
                "accesory": "Pihole",
                "name": "Pihole",
                "auth": "<API TOKEN>",
                "host": "192.168.18.6",
                "time": 120
        }
```

To the accessories section of my config.json and when I restart Homebridge in my Pi it says

```
TypeError: Cannot read property 'indexOf' of undefined
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:12)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at startup (internal/bootstrap/node.js:283:19)
Dec 03 16:49:41 raspberrypi homebridge[13561]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by arendruni** [comment]
Might be related to this [issue](https://github.com/nfarina/homebridge/issues/756#issuecomment-307920482)

**Comment by thewinger** [comment]
That was it.

Sorry for the waste of time.
